opt_in_rules: []
disabled_rules:
  - redundant_discardable_let
  - line_length
  - closure_parameter_position
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - opening_brace
  - file_length
  - type_body_length
  - function_body_length