opt_in_rules: []
disabled_rules:
  - todo
  - line_length
  - closure_parameter_position
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - opening_brace

file_length:
  warning: 500
  error: 600
