project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
files:
  - source: /Blankie/Localizable.xcstrings
    translation: /Blankie/Localizable.xcstrings
    type: string_catalog
    update_option: update_as_unapproved
bundles:
  - 1
