project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true
bundles:
  - 1
files:
  - source: "/Blankie/Localizable.xcstrings"
    translation: "/Blankie/Localizable.xcstrings"
    type: string_catalog
