name: Feature Request
description: Suggest an idea or improvement for Blankie
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

        We appreciate detailed feature requests that help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a problem? Please describe what you're trying to achieve.
      placeholder: "I'm always frustrated when I can't save multiple presets for different work scenarios..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as detailed as possible about how you imagine this feature working.
      placeholder: |
        I would like to see a preset manager where I can:
        - Save current sound mix as a named preset
        - Quick switch between presets from the menu bar
        - Set keyboard shortcuts for favorite presets
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "I've tried using AppleScript to automate this, but it's not ideal because..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Design Mockups
      description: If you have any mockups, sketches, or visual examples of your idea, please share them here. You can drag and drop images.
      placeholder: "Drag and drop images or paste them here"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: This helps us understand the impact of the feature
      options:
        - Not important, but should be considered
        - Nice to have
        - Would significantly improve my experience
        - Unusable without this feature
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, use cases, or examples about the feature request here.
      placeholder: "This feature would be especially useful for people who work in different environments throughout the day..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Let us know if you're interested in helping with this feature
      options:
        - label: I'm willing to help test this feature
          required: false
        - label: I'm interested in contributing code for this feature
          required: false
        - label: I can provide more detailed specifications or mockups if needed
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested
          required: true
        - label: I have clearly described the problem this feature would solve
          required: true
