name: Translation contribution
description: Submit language translations for Blankie
title: "[Translation]: "
labels: ["translation-contribution"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Blankie's translations!

        **Instructions:**
        1. Download a source template or current language translation from https://blankie.rest/i18n
        2. Edit the files to add or improve translations
        3. Upload your modified files using this form

  - type: input
    id: language
    attributes:
      label: Language
      description: Which language are you contributing translations for? If you know the specific language or region code, please use it. If you are submitting multiple languages, please create separate GitHub Issue for each language.
      placeholder: "e.g., fr, es, de it, ja, pt-BR, zh-CN, es-419, etc."
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: File Upload and Change Summary
      description: Use this space to upload files and briefly describe what translations you've added, improved or reviewed. You can also provide a link to where the files are hosted.
      placeholder: "e.g., Fixed the translation for 'Train', improved 5 sound-related terms, and translated 10 new strings."
    validations:
      required: true

  - type: textarea
    id: language_ability
    attributes:
      label: Language Proficiency (Optional)
      description: If you're suggesting alternatives to existing translations, sharing your language background helps us evaluate your contribution.
      placeholder: "e.g., native speaker living in Spain, or professional translator with experience in technical terminology"
    validations:
      required: false

  - type: input
    id: name
    attributes:
      label: Attribution (Optional)
      description: If you'd like to be credited for your contribution, please provide how you'd like your name to be displayed in the app. If you would not like to be credited, you can leave this section blank.
      placeholder: "e.g., Marie Dubois"
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: Additional Comments (Optional)
      description: Use this space to share any other information or context about your contribution.
      placeholder: "e.g., Some terms were difficult to translate due to lack of context."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Terms
      description: By submitting these translations, you agree that your contribution may be included in the Blankie app and that it will be covered by the same license as the app.
      options:
        - label: I understand that my contributions will be subject to the same license as the Blankie app and if accepted it may be included in the app.
          required: true
